### PR TITLE
Update 02_gcd.js

### PR DESCRIPTION
**Pull request by ateebkhan96**
Added the comments to the code for better understanding.

### CODE REVIEW

**Comment by polx** [comment]
Thanks for this PR. The comments sound to be useful.
I am wondering if this is a good idea to have a single source heavily commented like this and others not.

**Comment by ateebkhan96** [comment]
Dear Paul,

I am right now enrolled in the DLMCSA01 module, so as I practice the code
in the coursebook, I try to comment. So, in future you may get pull
requests for other code files as well.

**Comment by polx** [comment]
Thanks Ateeb,

So we’ll stay like this for now: no merge of the pull-request.

It’s certainly useful for your reflection to have a commented version 
of all the scripts but some may consider it too noisy.

Having the choice is probably the best.

Paul

**Comment by ateebkhan96** [comment]
Hey Paul,

Thank you for the feedback.

**Pull request closed without merging**
